sudo: false
language: go

go:
    - 1.6

script:
    - go get -t -v ./...
    - go test -v ./...
    - go build -a -o bin/courier courier
    - bzip2 --keep bin/courier
    - gzip -c bin/courier > bin/courier.gz

deploy:
  provider: releases
  api_key:
    secure: HFzYRhe9ELhK2MKbVDt0otaoKiPJWTVwXJfxW2HQGl9BabkP9fDnzEWQc3HAV342EFP1xqiOQiD8sl8O6WHwixg7jnvMXYkpR3ML+a6s2WVSPYfr8hiZnss61Vcp5xOpCr/0r1RI1b2ZwCSnIJfvbJ7jznkS0fZrkbcSS8mvYgqvFq08DcfYckk2EJioPu+Lq/DFUhOARZ+yDSd4ydClQi3GKE/XNsC1JY6TxHCtiALZKe90oPSEvIJhiCo5WoJym4jyMf8XFGVXE9zFYYfmQj76TWCaEwJhFp+EmlCNK3m4s9L9tBdxcwRr4rgXqJbJnCRHFjvVTetsXMnavTDpuUwxZzvct+ArVCuArNcecyu5N+RIOmlb0/ogavZv9yyjEereU3bw0x20AihoJ2cyzOoJ4MHzUzWjUaUYrD2HiFmf2opGQ5U3MyJRnl2iX5tPByQ0myIztKKSDsforB3hMJrI/5HjF4LB0DnOrmemO+ZZmVbuGAOqX9XTd/ssCPTLZJqoTJB+/zPnvd9SGV/AMRkEjjefCsvGQbQWKtYeZ7k4axYSBfj8pvbci6FCW+WqJ13mgWXDATORNW8YSmhWZG5odmW4yZ5l9ZoDv4mLJzejtKCZYi2Jnv12W885QgnIbhcGyKTEiTLF6x0OqjaOagFx9UD8a08gQMu4nDJyDIo=
  file:
      - bin/courier.gz
      - bin/courier.bz2
  on:
    repo: optiver/courier
